(load "Question.lisp")
(defvar str1)
(defvar str2)
(setq str1 (string "pale"))
(setq str2 (string "ple"))
(format t "~A, ~A => ~B~%" str1 str2 (oneEditAway str1 str2))
(write t)
(setq str1 (string "pales"))
(setq str2 (string "pale"))
(format t "~A, ~A => ~B~%" str1 str2 (oneEditAway str1 str2))
(write t)
(setq str1 (string "pale"))
(setq str2 (string "bale"))
(format t "~A, ~A => ~B~%" str1 str2 (oneEditAway str1 str2))
(write t)
(setq str1 (string "pale"))
(setq str2 (string "bae"))
(format t "~A, ~A => ~B~%" str1 str2 (oneEditAway str1 str2))
(write t)
